open Doc;;
open User1;;
open User2;;
open Fichier_zombies;;
open Demo1;;
open Demo2;;
open Demo3;;
open Demo4;;
open Demo5;;
make_xml "equipe1.xml" "1.0" "UTF-8" equipe1;;
make_xml "equipe2.xml" "1.0" "UTF-8" equipe2;;
make_xml "zombies.xml" "1.0" "UTF-8" zombies;;
make_xml "demo1.xml" "1.0" "UTF-8" demo1;;
make_xml "demo2.xml" "1.0" "UTF-8" demo2;;
make_xml "demo3.xml" "1.0" "UTF-8" demo3;;
make_xml "demo4.xml" "1.0" "UTF-8" demo4;;
make_xml "demo5.xml" "1.0" "UTF-8" demo5;;
make_xml "demo5_2.xml" "1.0" "UTF-8" demo5_2;;
